Traceback (most recent call last):
  File "c:\users\mugasi01\miniconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\mugasi01\miniconda3\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\mugasi01\miniconda3\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\mugasi01\miniconda3\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\mugasi01\miniconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\mugasi01\miniconda3\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "c:\users\mugasi01\miniconda3\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\mugasi01\miniconda3\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sympy import symbols
from sympy.physics.mechanics import ReferenceFrame
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_15132/2875602743.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0msympy[0m [1;32mimport[0m [0msymbols[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mfrom[0m [0msympy[0m[1;33m.[0m[0mphysics[0m[1;33m.[0m[0mmechanics[0m [1;32mimport[0m [0mReferenceFrame[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'sympy'
ModuleNotFoundError: No module named 'sympy'

