Traceback (most recent call last):
  File "/Users/inertialframe/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/inertialframe/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/inertialframe/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/inertialframe/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/inertialframe/opt/anaconda3/envs/qe-mini-example/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/inertialframe/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/inertialframe/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/inertialframe/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
r_vec.dt(A)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/var/folders/nv/1xnwf7gx3kx0c_dlh9wxbqkc0000gn/T/ipykernel_73452/1721655755.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mr_vec[0m[0;34m.[0m[0mdt[0m[0;34m([0m[0mA[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/sympy/physics/vector/vector.py[0m in [0;36mdt[0;34m(self, otherframe)[0m
[1;32m    648[0m         """
[1;32m    649[0m         [0;32mfrom[0m [0msympy[0m[0;34m.[0m[0mphysics[0m[0;34m.[0m[0mvector[0m [0;32mimport[0m [0mtime_derivative[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 650[0;31m         [0;32mreturn[0m [0mtime_derivative[0m[0;34m([0m[0mself[0m[0;34m,[0m [0motherframe[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    651[0m [0;34m[0m[0m
[1;32m    652[0m     [0;32mdef[0m [0msimplify[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/sympy/physics/vector/functions.py[0m in [0;36mtime_derivative[0;34m(expr, frame, order)[0m
[1;32m    200[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    201[0m                 outlist += (time_derivative(Vector([v]), v[1]) + \
[0;32m--> 202[0;31m                     (v[1].ang_vel_in(frame) ^ Vector([v]))).args
[0m[1;32m    203[0m         [0moutvec[0m [0;34m=[0m [0mVector[0m[0;34m([0m[0moutlist[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    204[0m         [0;32mreturn[0m [0mtime_derivative[0m[0;34m([0m[0moutvec[0m[0;34m,[0m [0mframe[0m[0;34m,[0m [0morder[0m [0;34m-[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/sympy/physics/vector/frame.py[0m in [0;36mang_vel_in[0;34m(self, otherframe)[0m
[1;32m    438[0m [0;34m[0m[0m
[1;32m    439[0m         [0m_check_frame[0m[0;34m([0m[0motherframe[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 440[0;31m         [0mflist[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_dict_list[0m[0;34m([0m[0motherframe[0m[0;34m,[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    441[0m         [0moutvec[0m [0;34m=[0m [0mVector[0m[0;34m([0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    442[0m         [0;32mfor[0m [0mi[0m [0;32min[0m [0mrange[0m[0;34m([0m[0mlen[0m[0;34m([0m[0mflist[0m[0;34m)[0m [0;34m-[0m [0;36m1[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/qe-mini-example/lib/python3.8/site-packages/sympy/physics/vector/frame.py[0m in [0;36m_dict_list[0;34m(self, other, num)[0m
[1;32m    320[0m [0;34m[0m[0m
[1;32m    321[0m         [0mmsg[0m [0;34m=[0m [0;34m'No connecting {} path found between {} and {}.'[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 322[0;31m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0mmsg[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mconnect_type[0m[0;34m[[0m[0mnum[0m[0;34m][0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mname[0m[0;34m,[0m [0mother[0m[0;34m.[0m[0mname[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    323[0m [0;34m[0m[0m
[1;32m    324[0m     [0;32mdef[0m [0m_w_diff_dcm[0m[0;34m([0m[0mself[0m[0;34m,[0m [0motherframe[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: No connecting angular velocity path found between B and A.
ValueError: No connecting angular velocity path found between B and A.

